name: CI

on:
  push:
    branches:
      - master
  release:
    types: [released]
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Release
    permissions:
      contents: write
    env:
      APP_NAME: idle_bolt
    strategy:
      matrix:
        target:
          # Windows
          - { displayName: 32-bit Windows,
              rustTarget: i686-pc-windows-gnu,
              runner: 'ubuntu-latest' }

          - { displayName: 64-bit Windows,
              rustTarget: x86_64-pc-windows-gnu,
              runner: 'ubuntu-latest' }

          # Linux
          - { displayName: 64-bit Linux,
              rustTarget: x86_64-unknown-linux-gnu,
              runner: 'ubuntu-latest' }

          # macOS
          - { displayName: 64-bit macOS,
              rustTarget: x86_64-apple-darwin,
              runner: 'macos-latest' }

    runs-on: ${{ matrix.target.runner }}
    steps:
      # Get the machine ready to build
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target.rustTarget }}

      - name: Update Sources
        if: ${{ contains(matrix.target.rustTarget, 'linux') }}
        run: sudo apt update

      - name: Add Global Dependencies
        if: ${{ contains(matrix.target.rustTarget, 'linux') }}
        run: sudo apt install -y libxdo-dev

      - name: Add Windows Build Dependencies
        if: ${{ contains(matrix.target.rustTarget, 'pc-windows') }}
        run: sudo apt install -y gcc-mingw-w64

      # Build time
      - name: Build
        run: cargo build --release --target ${{ matrix.target.rustTarget }}

      - name: Upload Asset
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP_NAME }}-${{ matrix.target.rustTarget }}${{ endsWith(matrix.target.rustTarget, '-windows-gnu') && '.exe' || '' }}
          path: ./target/${{ matrix.target.rustTarget }}/release/${{ env.APP_NAME }}${{ endsWith(matrix.target.rustTarget, '-windows-gnu') && '.exe' || '' }}

      - name: Upload Release Asset
        if: github.event_name == 'release'
        id: upload-release-asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cp ./target/${{ matrix.target.rustTarget }}/release/${{ env.APP_NAME }}${{ endsWith(matrix.target.rustTarget, '-windows-gnu') && '.exe' || '' }} ./${{ env.APP_NAME }}-${{ github.ref_name }}-${{ matrix.target.rustTarget }}${{ endsWith(matrix.target.rustTarget, '-windows-gnu') && '.exe' || '' }} &&
          gh release upload ${{ github.event.release.tag_name }} ./${{ env.APP_NAME }}-${{ github.ref_name }}-${{ matrix.target.rustTarget }}${{ endsWith(matrix.target.rustTarget, '-windows-gnu') && '.exe' || '' }}#"${{ env.APP_NAME }}-${{ github.ref_name }}-${{ matrix.target.rustTarget }}${{ endsWith(matrix.target.rustTarget, '-windows-gnu') && '.exe' || '' }} (${{ matrix.target.displayName }})"
